spring.application.name=medinova
  # ============================================================
  # SERVER CONFIG
  # ============================================================
  server.port=8080
  # ============================================================
  # DATASOURCE (MySQL)ackage com.example.medinova.Dao;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.example.medinova.Bean.Student;
@Repository
public interface
  # ============================================================
  spring.datasource.url=jdbc:mysql://localhost:3306/medinova
  spring.datasource.username=root
  spring.datasource.password=Shy007_mits29
  
  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
  # ============================================================
  # JPA / HIBERNATE
  # ============================================================
  spring.jpa.hibernate.ddl-auto=update       
  spring.jpa.show-sql=true
  spring.jpa.properties.hibernate.format_sql=true
  # ============================================================